### ISSUE TITLE
Unable to view, add, or import snippets or folders

### ISSUE THREAD

**Issue by jerred121** [tahabasri/snippets#68]
In the side bar I just see the add and import buttons, no snippets or folders.

Upon doing virtually anything related to the extension, I get the following error in the Extension Host output:

`2023-04-26 11:55:12.048 [error] TypeError: Cannot read properties of undefined (reading 'length')
    at Function.flatten (c:\Users\jreed\.vscode\extensions\tahabasri.snippets-3.0.0\dist\extension.js:2:28444)
    at s.getAllSnippets (c:\Users\jreed\.vscode\extensions\tahabasri.snippets-3.0.0\dist\extension.js:2:28913)
    at Object.provideCompletionItems (c:\Users\jreed\.vscode\extensions\tahabasri.snippets-3.0.0\dist\extension.js:2:18399)
    at _.provideCompletionItems (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:51686)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:71536
    at ce.s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:63614)
    at ce.$provideCompletionItems (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:71523)
    at c.N (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11655)
    at c.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:11373)
    at c.H (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:10415)
    at c.G (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:9432)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:8220
    at E.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at h.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
    at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
    at p.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14916)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:124:16654
    at E.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
    at h.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
    at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
    at p.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14916)
    at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:124:14780)
    at MessagePortMain.emit (node:events:526:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)`

The following is the output I get from an export and the *_pre-import-bak.json from attempting an import:

`{"id":1,"parentId":-1,"label":"snippets"}`

Additionally, I get the following message when I try to import:

> Snippets weren't imported. Please check the file content or redo a proper export/import (A copy of your old snippets was saved next to the recently imported file)

As far as I can recall, I don't think the extension has ever worked for me.

I have settings sync turned enabled.

### VSCode About:
**Version:** 1.77.3 (system setup)
**Commit:** 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
**Date:** 2023-04-12T09:16:02.548Z (2 wks ago)
**Electron:** 19.1.11
**Chromium:** 102.0.5005.196
**Node.js:** 16.14.2
**V8:** 10.2.154.26-electron.0
**OS:** Windows_NT x64 10.0.19045
**Sandboxed:** No

Please let me know if you need any more info, I'd really like to use this extension, thanks.

**Comment by tahabasri** [comment]
Thanks @jerred121 for the report, I'll help you out fix the issue, if you don't have a snippet yet, you can try a clean install:
- Turn Off Settings Sync for Snippets extension.
- Uninstall the extension
- Remove cache files (if any), in your case for Windows that would be in "c:\\Users\\tahab\\AppData\\Roaming\\Code\\User\\globalStorage\\tahabasri.snippets\\" (remove whole folder if it exists)
- Reinstall the extension again and try it out

Let me know if that fixes your issue.

**Comment by jerred121** [comment]
Thank you for the response @tahabasri, apologies for such a long delay on getting back to you...

I followed your instructions and now when I try "Add Snippet" or "Add Snippet Folder," enter the name, and press Enter, I get the following Extension Host error: 

```
[error] TypeError: Cannot read properties of undefined (reading 'push')
    at s.addSnippet (c:\Users\jreed\.vscode\extensions\tahabasri.snippets-3.0.0\dist\extension.js:2:29260)
    at t.SnippetsProvider.addSnippet (c:\Users\jreed\.vscode\extensions\tahabasri.snippets-3.0.0\dist\extension.js:2:26172)
    at Object.<anonymous> (c:\Users\jreed\.vscode\extensions\tahabasri.snippets-3.0.0\dist\extension.js:2:8304)
    at Generator.next (<anonymous>)
    at r (c:\Users\jreed\.vscode\extensions\tahabasri.snippets-3.0.0\dist\extension.js:2:6251)
```

**Comment by tahabasri** [comment]
@jerred121 please try this new feature, if there are some dangling snippets, they will be extracted and that may fix your issue.
https://raw.githubusercontent.com/tahabasri/snippets/main/images/features/67-fix-snippets.gif

**Comment by tahabasri** [comment]
@jerred121 enhanced the troubleshooting feature so it fixes any duplicates and/or corrupted snippets. Feel free to reopen this issue if the new feature wouldn't help you.
